import { useEffect, useState, type FormEvent } from 'react';
import { X, CheckCircle, Send, Mail, Phone, MessageCircle, AlertCircle } from 'lucide-react';

const CONTACT_INFO = { email: 'coalesceuniversity@gmail.com', phoneDisplay: '+27 83 249 2219', phoneHref: 'tel:+27832492219', whatsappHref: 'https://wa.me/27832492219' };
interface ContactFormData { name:string; email:string; phone:string; service:string; budget:string; message:string; website:string; }
const initialFormData:ContactFormData={name:'',email:'',phone:'',service:'',budget:'R 5,000 - R 15,000',message:'',website:''};

export function ContactModal({isOpen,onClose,initialService}:{isOpen:boolean;onClose:()=>void;initialService?:string}) {
 const [formData,setFormData]=useState(initialFormData); const [submitted,setSubmitted]=useState(false); const [submitting,setSubmitting]=useState(false); const [submitError,setSubmitError]=useState('');
 useEffect(()=>{if(initialService)setFormData(p=>({...p,service:initialService}))},[initialService]);
 useEffect(()=>{if(!isOpen)return;const previous=document.body.style.overflow;const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.body.style.overflow='hidden';document.addEventListener('keydown',escape);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',escape)}},[isOpen,onClose]);
 if(!isOpen)return null;
 const update=(field:keyof ContactFormData,value:string)=>{setFormData(p=>({...p,[field]:value}));setSubmitError('')};
 const submit=async(e:FormEvent)=>{e.preventDefault();setSubmitError('');if(formData.website.trim())return;const url=import.meta.env.VITE_CONTACT_WEBHOOK_URL as string|undefined;if(!url){const subject=encodeURIComponent('New Coalesce Digital enquiry'+(formData.service?' — '+formData.service:''));const body=encodeURIComponent(['Name: '+formData.name,'Email: '+formData.email,'Phone / WhatsApp: '+(formData.phone||'Not provided'),'Service: '+(formData.service||'Not specified'),'Budget: '+(formData.budget||'Not specified'),'','Project Scope & Goals:',formData.message].join('\n'));window.location.href='mailto:'+CONTACT_INFO.email+'?subject='+subject+'&body='+body;return}setSubmitting(true);try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...formData,source:'coalesce-digital-website',submittedAt:new Date().toISOString(),page:window.location.href})});if(!response.ok)throw new Error(String(response.status));setSubmitted(true)}catch(error){console.error(error);setSubmitError('We could not send your inquiry right now. Please email us directly or try again in a moment.')}finally{setSubmitting(false)}};
 return <div className="fixed inset-0 z-[1000] flex items-center justify-center p-4 sm:p-6 bg-black/60 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}>
  <div className="relative w-full max-w-2xl bg-white rounded-3xl p-6 sm:p-10 shadow-2xl border border-neutral-200 max-h-[90vh] overflow-y-auto" role="dialog" aria-modal="true" aria-labelledby="contact-modal-title">
   <button type="button" onClick={onClose} className="absolute top-6 right-6 w-10 h-10 rounded-full bg-neutral-100 flex items-center justify-center" aria-label="Close contact form"><X className="w-5 h-5"/></button>
   {submitted?<div className="py-12 flex flex-col items-center text-center gap-4"><div className="w-16 h-16 rounded-full bg-black text-white flex items-center justify-center"><CheckCircle className="w-8 h-8 text-[#b3de4f]"/></div><h2 id="contact-modal-title" className="font-antonio font-bold uppercase text-3xl sm:text-4xl">Inquiry received.</h2><p className="text-sm text-neutral-600 max-w-md">Thank you, <strong className="text-black">{formData.name}</strong>. Your project details have been sent. We will respond as soon as possible.</p><button type="button" onClick={()=>{setSubmitted(false);setFormData(initialFormData);onClose()}} className="mt-6 px-8 py-3 rounded-full bg-black text-white text-xs font-semibold uppercase tracking-widest">Back to site</button></div>
   :<div><div className="mb-8"><span className="font-satisfy text-lg text-neutral-500 block mb-1">Start a Conversation</span><h2 id="contact-modal-title" className="font-antonio font-bold uppercase text-4xl sm:text-5xl tracking-tight">Let's Build Something Exceptional</h2><p className="text-xs sm:text-sm text-neutral-500 mt-2">Choose the fastest way to reach us, or send your project details below.</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 mt-6"><a href={CONTACT_INFO.phoneHref} className="levitate rounded-2xl bg-black text-white px-4 py-3 flex items-center justify-center gap-2 text-[10px] font-bold uppercase tracking-widest"><Phone size={15}/> Call us</a><a href={CONTACT_INFO.whatsappHref} target="_blank" rel="noopener noreferrer" className="levitate rounded-2xl bg-[#25D366] text-black px-4 py-3 flex items-center justify-center gap-2 text-[10px] font-bold uppercase tracking-widest"><MessageCircle size={15}/> WhatsApp</a><a href={"mailto:"+CONTACT_INFO.email} className="levitate rounded-2xl border border-black/15 bg-neutral-50 px-4 py-3 flex items-center justify-center gap-2 text-[10px] font-bold uppercase tracking-widest"><Mail size={15}/> Email</a></div><div className="mt-4 mb-2 text-center text-xs text-neutral-500"><a href={CONTACT_INFO.phoneHref} className="font-semibold text-black">{CONTACT_INFO.phoneDisplay}</a> <span className="mx-2">•</span> <a href={"mailto:"+CONTACT_INFO.email}>{CONTACT_INFO.email}</a></div></div>
   <form onSubmit={submit} className="flex flex-col gap-4 sm:gap-5 text-xs sm:text-sm">
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field id="contact-name" label="Your Name *" type="text" value={formData.name} onChange={v=>update('name',v)} required/><Field id="contact-email" label="Email Address *" type="email" value={formData.email} onChange={v=>update('email',v)} required/></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field id="contact-phone" label="Phone / WhatsApp" type="tel" value={formData.phone} onChange={v=>update('phone',v)}/><Select id="contact-service" label="Service or Package" value={formData.service} onChange={v=>update('service',v)} options={['Web & Apps','Automation','Social Media','Digital Design & Marketing','Launch Package','Growth Package','Scale Package','Custom Scope']}/></div>
    <Select id="contact-budget" label="Budget Range" value={formData.budget} onChange={v=>update('budget',v)} options={['Under R 5,000','R 5,000 - R 15,000','R 15,000 - R 35,000','R 35,000+']}/>
    <div><label htmlFor="contact-message" className="block text-xs font-semibold uppercase tracking-wider text-neutral-700 mb-1.5">Project Scope & Goals *</label><textarea id="contact-message" required rows={4} value={formData.message} onChange={e=>update('message',e.target.value)} className="w-full px-4 py-3 rounded-xl border border-neutral-300 outline-none bg-neutral-50 focus:bg-white" placeholder="Tell us about your brand, timeline and goals..."/></div>
    <div className="hidden" aria-hidden="true"><label htmlFor="contact-website">Website</label><input id="contact-website" tabIndex={-1} autoComplete="off" value={formData.website} onChange={e=>update('website',e.target.value)}/></div>
    {submitError&&<div className="flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-red-700" role="alert"><AlertCircle className="w-4 h-4 mt-0.5 shrink-0"/><p>{submitError}</p></div>}
    <div className="pt-2 flex flex-col sm:flex-row items-center justify-between gap-4"><a href={"mailto:"+CONTACT_INFO.email} className="flex items-center gap-2 text-neutral-500"><Mail className="w-3.5 h-3.5"/> Email Direct</a><button type="submit" disabled={submitting} className="w-full sm:w-auto px-8 py-3.5 rounded-full bg-black text-white text-xs font-bold uppercase tracking-widest flex items-center justify-center gap-2 disabled:opacity-50">{submitting?'Sending...':<>Send Message<Send className="w-3.5 h-3.5"/></>}</button></div>
   </form></div>}
  </div></div>;
}
function Field({id,label,type,value,onChange,required=false}:{id:string;label:string;type:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <div><label htmlFor={id} className="block text-xs font-semibold uppercase tracking-wider text-neutral-700 mb-1.5">{label}</label><input id={id} type={type} required={required} autoComplete={type==='email'?'email':type==='tel'?'tel':'name'} value={value} onChange={e=>onChange(e.target.value)} className="w-full px-4 py-3 rounded-xl border border-neutral-300 outline-none bg-neutral-50 focus:bg-white"/></div>}
function Select({id,label,value,onChange,options}:{id:string;label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <div><label htmlFor={id} className="block text-xs font-semibold uppercase tracking-wider text-neutral-700 mb-1.5">{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)} className="w-full px-4 py-3 rounded-xl border border-neutral-300 outline-none bg-neutral-50 focus:bg-white"><option value="">Select an area...</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></div>}
